# Generated by Django 3.0.5 on 2021-02-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210131_0724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
