# Generated by Django 3.0.5 on 2021-03-02 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user',
            new_name='author',
        ),
    ]
